<div class="row">
	<div class="col">
        <div class="card mb-4">
        <?php
        $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Update Record</b>
        		</div>
        	</div>
        	
        	<div class="card-body">
        		<?php echo $this->formCollection($this->form); ?>
        	</div>
        <?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
	<div class="col mb-4">
		<?php $this->boxFiles()->setTitle($this->files_title)->setData($this->files)->setReference($this->files_reference)->setVariable('actionMenu', $actionMenu)->render(); ?>
	</div>
</div>
<div class="row">
	<div class="col mb-4">
		<?php echo $this->annotations()->setAnnotations($this->annotations)->render(); ?>
	</div>

</div>
   