<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-3 mb-3 bg-light rounded-3">
	<div class="container-fluid py-5">
        <h1 class="display-5 fw-bold placeholder-glow"><span class="placeholder col-7"></span></h1>
    
        <p class="placeholder-glow">
            <span class="placeholder col-4"></span>
        </p>
    
        <hr class="my-4">
    
        <a class="btn btn-primary btn-lg" href="#" target="_blank">Wikipedia &raquo;</a>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-3">
	<div class="col">
        <div class="card h-100">
            <h2 class="card-header">Step 1: Login</h2>
            <div class="card-body">
                <p>
                    Log into the application using the same credentials (username and password) you log into your workstation with.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('user/login'); ?>">Login &raquo;</a>
            </div>
        </div>
    </div>

	<div class="col">
        <div class="card h-100">
            <h2 class="card-header">Step 2: Inspection</h2>
            <div class="card-body">
                <p>
                    Enter your inspections in the log form.  Add additional notes using the tools at the bottom of the form.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('inspections/default'); ?>">Inspections &raquo;</a>
            </div>
        </div>
    </div>

	<div class="col">
        <div class="card h-100">
            <h2 class="card-header">Help &amp; Support</h2>
            <div class="card-body">
                <p>
                    If you are having trouble with your application, please submit a Help Desk Ticket by following the link below.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="https://kbox.midnet.cityofmiddletown.com/" target="_blank">Submit Ticket &raquo;</a>
            </div>
        </div>
    </div>
</div>