<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to the<br>Inspection Log Application</h1>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Step 1: Login</h2>
        <div class="card-body">
            <p>
                Log into the application using the same credentials (username and password) you log into your workstation with.
            </p>
        </div>
        <div class="card-footer">
        	<a class="btn btn-primary" href="<?php echo $this->url('user/login'); ?>">Login &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Step 2: Inspection</h2>
        <div class="card-body">
            <p>
                Enter your inspections in the log form.  Add additional notes using the tools at the bottom of the form.
            </p>
        </div>
        <div class="card-footer">
        	<a class="btn btn-primary" href="<?php echo $this->url('inspections/default'); ?>">Inspections &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Help &amp; Support</h2>
        <div class="card-body">
            <p>
                If you are having trouble with your application, please submit a Help Desk Ticket by following the link below.
            </p>
        </div>
        <div class="card-footer">
        	<a class="btn btn-primary" href="https://kbox.midnet.cityofmiddletown.com/" target="_blank">Submit Ticket &raquo;</a>
        </div>
    </div>
</div>
